#!/usr/bin/env python3
import os
if 'OMP_NUM_THREADS' not in os.environ:
    os.environ['OMP_NUM_THREADS'] = '1'
if 'MKL_NUM_THREADS' not in os.environ:
    os.environ['MKL_NUM_THREADS'] = '1'

import sys
import time

from PyQt5 import QtCore
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QApplication

from ManifoldEM import p
from ManifoldEM.gui import MainWindow

p.proj_name = time.strftime("%Y%m%d_%H%M%S")

if __name__ == '__main__':
    print(r"""
 __  __             _  __       _     _ _____ __  __
|  \/  | __ _ _ __ (_)/ _| ___ | | __| | ____|  \/  |
| |\/| |/ _` | '_ \| | |_ / _ \| |/ _` |  _| | |\/| |
| |  | | (_| | | | | |  _| (_) | | (_| | |___| |  | |
|_|  |_|\__,_|_| |_|_|_|  \___/|_|\__,_|_____|_|  |_|

""")
    app = QApplication([])
    app.setStyle('fusion')
    app.setFont(QFont('Arial', 12))

    QtCore.QCoreApplication.setApplicationName('ManifoldEM')

    w = MainWindow()
    w.setWindowTitle('ManifoldEM')
    sys.exit(app.exec_())
